// <auto-generated />
using System;
using CRM.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Data.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20261002142642_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRM.Data.Models.ActividadLog", b =>
                {
                    b.Property<long>("nActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_actividad");

                    b.Property<string>("cAccion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_accion");

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cValorAnterior")
                        .HasColumnType("longtext")
                        .HasColumnName("c_valor_anterior");

                    b.Property<string>("cValorNuevo")
                        .HasColumnType("longtext")
                        .HasColumnName("c_valor_nuevo");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nEntidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("n_entidad_id");

                    b.Property<int?>("nUsuario")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario");

                    b.HasKey("nActividad");

                    b.HasIndex("dFecha");

                    b.HasIndex("cEntidad", "nEntidadId");

                    b.HasIndex("nUsuario", "dFecha");

                    b.ToTable("crm_actividad_log", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Campana", b =>
                {
                    b.Property<long>("nCampana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_campana");

                    b.Property<string>("cDescripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("c_descripcion");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_estado");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_tipo");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<DateTime?>("dFechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_fin");

                    b.Property<DateTime>("dFechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_inicio");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nCampana");

                    b.HasIndex("nAsignadoA");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_campana", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.CampanaCliente", b =>
                {
                    b.Property<long>("nCampana")
                        .HasColumnType("bigint")
                        .HasColumnName("n_campana");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_estado");

                    b.Property<DateTime>("dFechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_asignacion");

                    b.HasKey("nCampana", "nCliente");

                    b.HasIndex("nCliente");

                    b.ToTable("crm_campana_cliente", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Cliente", b =>
                {
                    b.Property<long>("nCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<string>("cCanalOrigen")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_canal_origen");

                    b.Property<string>("cDocumento")
                        .HasColumnType("longtext")
                        .HasColumnName("c_documento");

                    b.Property<string>("cEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("c_email");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cFotoPerfilUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("c_foto_perfil_url");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cTelefono")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_telefono");

                    b.Property<DateTime>("dFechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_registro");

                    b.HasKey("nCliente");

                    b.HasIndex("cCanalOrigen", "dFechaRegistro");

                    b.HasIndex("dFechaRegistro");

                    b.ToTable("crm_cliente", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ClienteEtiqueta", b =>
                {
                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<int>("nEtiqueta")
                        .HasColumnType("int")
                        .HasColumnName("n_etiqueta");

                    b.Property<DateTime>("dFechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_asignacion");

                    b.HasKey("nCliente", "nEtiqueta");

                    b.HasIndex("nEtiqueta");

                    b.ToTable("crm_cliente_etiqueta", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.Property<long>("nConversacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<string>("cBotEstado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_bot_estado");

                    b.Property<string>("cCanal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_canal");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cExternalThreadId")
                        .HasColumnType("longtext")
                        .HasColumnName("c_external_thread_id");

                    b.Property<string>("cPhoneNumberId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("c_phone_number_id");

                    b.Property<DateTime?>("dBotPausadoDesde")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_bot_pausado_desde");

                    b.Property<DateTime>("dFechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_inicio");

                    b.Property<DateTime?>("dUltimoMensaje")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_ultimo_mensaje");

                    b.Property<DateTime?>("dUltimoMensajeCliente")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_ultimo_mensaje_cliente");

                    b.Property<int?>("nBotPausadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_bot_pausado_por");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<int?>("nUsuarioAsignado")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario_asignado");

                    b.HasKey("nConversacion");

                    b.HasIndex("nCliente");

                    b.HasIndex("cCanal", "cEstado", "dUltimoMensaje");

                    b.HasIndex("dFechaInicio");

                    b.HasIndex("nUsuarioAsignado", "cEstado", "dUltimoMensaje");

                    b.ToTable("crm_conversacion", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.CrmUsuario", b =>
                {
                    b.Property<int>("nUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("n_usuario");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cPasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("c_password_hash");

                    b.Property<string>("cRol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_rol");

                    b.Property<string>("cUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_usuario");

                    b.HasKey("nUsuario");

                    b.ToTable("crm_usuario", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Etiqueta", b =>
                {
                    b.Property<int>("nEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("n_etiqueta");

                    b.Property<string>("cColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_color");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("c_nombre");

                    b.HasKey("nEtiqueta");

                    b.HasIndex("cNombre")
                        .IsUnique();

                    b.ToTable("crm_etiqueta", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.KpiDashboard", b =>
                {
                    b.Property<long>("nKpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_kpi");

                    b.Property<string>("cMeta")
                        .HasColumnType("longtext")
                        .HasColumnName("c_meta");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cPeriodo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_periodo");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_tipo");

                    b.Property<string>("cValor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_valor");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.HasKey("nKpi");

                    b.ToTable("crm_kpi_dashboard", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.LoginAttempt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("c_key");

                    b.Property<DateTime?>("BlockedUntilUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_blocked_until_utc");

                    b.Property<int>("Failures")
                        .HasColumnType("int")
                        .HasColumnName("n_failures");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_updated_utc");

                    b.HasKey("Key");

                    b.ToTable("crm_login_attempt", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Mensaje", b =>
                {
                    b.Property<long>("nMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_mensaje");

                    b.Property<string>("cCanal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_canal");

                    b.Property<string>("cDireccion")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("c_direccion");

                    b.Property<string>("cEstado")
                        .HasColumnType("longtext")
                        .HasColumnName("c_estado");

                    b.Property<string>("cExternalId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("c_external_id");

                    b.Property<string>("cMensaje")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_mensaje");

                    b.Property<string>("cReplyToExternalId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("c_reply_to_external_id");

                    b.Property<string>("cTipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("c_tipo");

                    b.Property<string>("cWhatsappId")
                        .HasColumnType("longtext")
                        .HasColumnName("c_whatsapp_id");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.HasKey("nMensaje");

                    b.HasIndex("nConversacion", "dFecha");

                    b.HasIndex("cCanal", "cDireccion", "cExternalId")
                        .IsUnique();

                    b.HasIndex("cTipo", "cCanal", "dFecha");

                    b.HasIndex("dFecha");

                    b.HasIndex("nConversacion", "cTipo", "cReplyToExternalId", "dFecha");

                    b.ToTable("crm_mensaje", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.NotaInterna", b =>
                {
                    b.Property<long>("nNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_nota");

                    b.Property<string>("cTexto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_texto");

                    b.Property<DateTime>("dFecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nNota");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_nota_interna", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Oportunidad", b =>
                {
                    b.Property<long>("nOportunidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_oportunidad");

                    b.Property<string>("cEtapa")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_etapa");

                    b.Property<string>("cMoneda")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_moneda");

                    b.Property<string>("cMotivoPerdida")
                        .HasColumnType("longtext")
                        .HasColumnName("c_motivo_perdida");

                    b.Property<string>("cTitulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_titulo");

                    b.Property<DateTime?>("dFechaActualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_actualizacion");

                    b.Property<DateTime?>("dFechaCierreEstimada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_cierre_estimada");

                    b.Property<DateTime?>("dFechaCierreReal")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_cierre_real");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<long>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.Property<decimal>("nMonto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("n_monto");

                    b.Property<int>("nProbabilidad")
                        .HasColumnType("int")
                        .HasColumnName("n_probabilidad");

                    b.Property<int?>("nUsuarioAsignado")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario_asignado");

                    b.HasKey("nOportunidad");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nUsuarioAsignado", "cEtapa", "dFechaCierreEstimada");

                    b.HasIndex("dFechaCreacion");

                    b.ToTable("crm_oportunidad", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ReglaAutomatica", b =>
                {
                    b.Property<long>("nRegla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_regla");

                    b.Property<bool>("bActiva")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("b_activa");

                    b.Property<string>("cAccion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_accion");

                    b.Property<string>("cCondicion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_condicion");

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cEvento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_evento");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cValorAccion")
                        .HasColumnType("longtext")
                        .HasColumnName("c_valor_accion");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nRegla");

                    b.HasIndex("nAsignadoA");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_regla_automatica", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ReporteExportacion", b =>
                {
                    b.Property<long>("nReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_reporte");

                    b.Property<string>("cEntidad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_entidad");

                    b.Property<string>("cNombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_nombre");

                    b.Property<string>("cRuta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_ruta");

                    b.Property<string>("cTipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_tipo");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.HasKey("nReporte");

                    b.HasIndex("nCreadoPor");

                    b.ToTable("crm_reporte_exportacion", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.Tarea", b =>
                {
                    b.Property<long>("nTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("n_tarea");

                    b.Property<string>("cDescripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("c_descripcion");

                    b.Property<string>("cEstado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("c_estado");

                    b.Property<string>("cTitulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("c_titulo");

                    b.Property<DateTime?>("dFechaCompletada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_completada");

                    b.Property<DateTime>("dFechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_creacion");

                    b.Property<DateTime>("dFechaVencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_vencimiento");

                    b.Property<int?>("nAsignadoA")
                        .HasColumnType("int")
                        .HasColumnName("n_asignado_a");

                    b.Property<long?>("nCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("n_cliente");

                    b.Property<long?>("nConversacion")
                        .HasColumnType("bigint")
                        .HasColumnName("n_conversacion");

                    b.Property<int?>("nCreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_creado_por");

                    b.Property<long?>("nOportunidad")
                        .HasColumnType("bigint")
                        .HasColumnName("n_oportunidad");

                    b.HasKey("nTarea");

                    b.HasIndex("nCliente");

                    b.HasIndex("nConversacion");

                    b.HasIndex("nOportunidad");

                    b.HasIndex("nAsignadoA", "cEstado", "dFechaVencimiento");

                    b.HasIndex("dFechaCreacion");

                    b.ToTable("crm_tarea", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.UsuarioPermiso", b =>
                {
                    b.Property<int>("nUsuario")
                        .HasColumnType("int")
                        .HasColumnName("n_usuario");

                    b.Property<string>("cPermiso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("c_permiso");

                    b.Property<DateTime>("dFechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("d_fecha_asignacion");

                    b.Property<int?>("nOtorgadoPor")
                        .HasColumnType("int")
                        .HasColumnName("n_otorgado_por");

                    b.HasKey("nUsuario", "cPermiso");

                    b.HasIndex("nOtorgadoPor");

                    b.ToTable("crm_usuario_permiso", (string)null);
                });

            modelBuilder.Entity("CRM.Data.Models.ActividadLog", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("nUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRM.Data.Models.Campana", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsignadoA");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.CampanaCliente", b =>
                {
                    b.HasOne("CRM.Data.Models.Campana", "Campana")
                        .WithMany()
                        .HasForeignKey("nCampana")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campana");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CRM.Data.Models.ClienteEtiqueta", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Etiqueta", "Etiqueta")
                        .WithMany("Clientes")
                        .HasForeignKey("nEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany("Conversaciones")
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.CrmUsuario", "UsuarioAsignado")
                        .WithMany("ConversacionesAsignadas")
                        .HasForeignKey("nUsuarioAsignado");

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("CRM.Data.Models.Mensaje", b =>
                {
                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("CRM.Data.Models.NotaInterna", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.Oportunidad", b =>
                {
                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "UsuarioAsignado")
                        .WithMany()
                        .HasForeignKey("nUsuarioAsignado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("CRM.Data.Models.ReglaAutomatica", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsignadoA");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.ReporteExportacion", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("nCreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("CRM.Data.Models.Tarea", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("nAsignadoA")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Data.Models.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("nConversacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.Oportunidad", "Oportunidad")
                        .WithMany()
                        .HasForeignKey("nOportunidad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AsignadoA");

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("CRM.Data.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("CRM.Data.Models.CrmUsuario", "OtorgadoPor")
                        .WithMany()
                        .HasForeignKey("nOtorgadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Data.Models.CrmUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("nUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OtorgadoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRM.Data.Models.Cliente", b =>
                {
                    b.Navigation("Conversaciones");
                });

            modelBuilder.Entity("CRM.Data.Models.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("CRM.Data.Models.CrmUsuario", b =>
                {
                    b.Navigation("ConversacionesAsignadas");
                });

            modelBuilder.Entity("CRM.Data.Models.Etiqueta", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
